version: '2'

services: 
  # starts only this one
  web:
    build:
      context: .
      dockerfile: php-mysql-apache.Dockerfile
    depends_on:
      - mysql
    volumes:
      - ../:/var/www/html
    ports:
      - 8000:80
      
  mysql: 
    image: mysql:5.7
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ywc_reunion8
    volumes:
      - ./mysql-data:/var/lib/mysql

  test:
    extends: npm
    entrypoint: gosu ${UID}:${UID} touch
    command: a

  watch:
    extends: npm
    entrypoint: gosu ${UID}:${UID} npm run watch

  # be run at runtime
  composer:
    build: 
      context: .
      dockerfile: composer.Dockerfile
    entrypoint: gosu ${UID}:${UID} composer
    command: install
    working_dir: /app
    volumes:
      - ../:/app

  npm:
    build: 
      context: .
      dockerfile: node.Dockerfile
    entrypoint: gosu ${UID}:${UID} npm
    command: install
    working_dir: /app
    volumes:
      - ../:/app

  php:
    build:
      context: .
      dockerfile: php-mysql-apache.Dockerfile
    entrypoint: gosu ${UID}:${UID} php
    working_dir: /app
    volumes:
      - ../:/app

  # helper service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8080:80
    links:
      - mysql:db
